spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Nirallan@2023
    url: jdbc:mysql://localhost:3306/sbms
    username: root
  jpa:
    show-sql: true
    
    hibernate:
      ddl-auto: update